# Generated by Django 2.0.5 on 2018-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_treasure_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='default.png', upload_to='treasure_images'),
        ),
    ]
